server:
  port: 5605


spring:
  datasource:
    url: jdbc:mysql://192.168.0.111:3306/hongyee_chronicdisease?serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: ENC(/lXBFbslJkThkrWwwY30cgSRWLEv5Rhq)
    password: ENC(zzFrQZ5rWHiNtQ7TsauhZgQ6mpJp0bPW)

eureka:
  client:
    #是否注册到eureka
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://eurekauser:jc~eu30991A@192.168.0.241:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    #续约时间，该时间越小，那么新注册的服务，就越快的能被访问到
    lease-renewal-interval-in-seconds: 5
    #过期时间
    lease-expiration-duration-in-seconds: 10

redisson:
  address: redis://192.168.0.111:6379
  password:

jointcorp:
  parent:
    debug: true
    ossBucketName: szjointcorptest
    ossEndpoint: oss-cn-shenzhen.aliyuncs.com

appconf:
#  remoteHost: http://192.168.0.111:8090/outside-service-local
#  usercenter: http://192.168.0.15:5595/jcloud/user
  #文件基础url
  file-base-url: https://szjointcorptest.oss-cn-shenzhen.aliyuncs.com

logging:
  config: classpath:logback-spring.xml
  logPath: D:/logs/hongyee-chronicdisease
  #不带扩展名
  logName: hongyee-chronicdisease